# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'stolzbernadette.github.io'
baseurl: ''
title: 'Bernadette Stolz'
description: 'Personal Website of Bernadette Stolz, Researcher in Topological Data Analysis for Biomedicine at the Max Planck Institute for Biochemistry'
permalink: pretty
logo: "/images/Logo2.jpg"
twitter: StolzBernadette
github:  stolzbernadette

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Group
  url: /group/
- title: Publications
  url: /publications/
- title: News
  url: /news/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "News from the group"
    feature_text: |
      Welcome to my personal website
    feature_image: "image/background_image/IMG_9380.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
